---
# Create user
- name: Copy the pg_hba conf
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/10/main/pg_hba.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Copy the postgres conf
  copy:
    src: postgresql.conf
    dest: /etc/postgresql/10/main/postgresql.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: enable and start postgresql
  systemd:
     name: postgresql
     state: started
     enabled: yes

- name: Create database user
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: SUPERUSER
    encrypted: yes

- name: Create database
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    encoding: UTF-8
    owner: "{{ db_user }}"

- name: restart postgresql
  systemd:
     name: postgresql
     state: restarted

# tasks file for postgresql
