---
- hosts: stage_host

  tasks:
          - name: Get date
            command: /bin/date
            changed_when: False
            register: date

          - debug: var={{ item }}
            with_items: 
                    - date.stdout
