---
- hosts: all
  become: true

  tasks:

    - name: Install required system packages
      yum: name={{ item }} state=latest update_cache=yes
      loop: [ 'epel-release']

    - name: Install required system packages
      yum: name={{ item }} state=latest update_cache=yes
      loop: [ 'curl', 'python', 'python-pip', 'python3', 'python3-pip' ]

    - name: install docker-py library for python
      raw: pip install docker
   
    - name: log into private docker registry
      docker_login:
           registry: "10.0.0.136:5000"
           username: "ctm"
           password: "ctm"
