---
- name: deploy
  hosts: app
  become: true
  vars:
    db_host: 10.132.0.54
  tasks:
    - name: Fetch the latest version of application code 
      git:
        repo: 'https://github.com/express42/reddit.git' 
        dest: /home/ctm/reddit
        version: monolith # <-- Указываем нужную ветку
      tags: deploy-tag 
      notify: reload puma

    - name: Bundle install 
      bundler:
        state: present
        chdir: /home/ctm/reddit
      tags: deploy-tag

  handlers: # <-- Добавим блок handlers и задачу 
  - name: reload puma
    systemd: name=puma state=restarted 